name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Auto-format code
        run: black src/
        
      - name: Lint code with flake8 (ignoring E501)
        run: flake8 src/ --ignore=E501

      - name: Run Retraining Script
        id: retrain
        run: |
          python src/model_retraining_and_mlflow_registering.py
        continue-on-error: false

      - name: Check if retraining was skipped
        id: check_retrain
        run: |
          python src/model_retraining_and_mlflow_registering.py
          status=$?
          if [ $status -eq 0 ]; then
            echo "status=trained" >> $GITHUB_OUTPUT
          else
            echo "status=skipped" >> $GITHUB_OUTPUT
          fi
      - name: Step 2 - Use output
        run: echo "${{ steps.check_retrain.outputs.status }}"

      #- name: Run tests
      #  run: pytest test_api_cicd.py

      #- name: Build Docker image
       # run: docker build --no-cache -t harshanant8876/iris-species-classifier-app .

      #- name: Login to Docker Hub
       # run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      #- name: Push Docker image
       # run: docker push harshanant8876/iris-species-classifier-app






