name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Auto-format code
        run: black src/
        
      - name: Lint code with flake8 (ignoring E501)
        run: flake8 src/ --ignore=E501


      #- name: Run tests
      #  run: pytest test_api_cicd.py

      - name: Build Docker image
        run: docker build -t iris-species-classifier-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push iris-species-classifier-app
